### ISSUE TITLE
Change User

### ISSUE THREAD

**Issue by databoy2k** [4v3ngR/aLauncher#1]
It would be really helpful if the user switcher could be implemented as well. My wife and I each use the CCWGTV and have our accounts linked to it.

Is that a difficult feature to add?

Thanks for what you've done - this is definitely the right changes to FLauncher. It's super fast!

**Comment by 4v3ngR** [comment]
Thanks for the feedback. I did some researching on the user change functionality of the CCWGTV and it appears that that is all rolled into the default google TV launcher, so when that is disabled, the account changing ability is also disabled. Here's a good example of the issue (and the impact of having the user switch bundled in the default home screen):

https://gitlab.com/flauncher/flauncher/-/issues/101

**Comment by databoy2k** [comment]
Got it. I guess this gets closed with "no fix available". Thanks for looking into it!
